// data.js
export const courses = [
  {
    subject: "مباحثی در الگوریتم ها",
    credits: 3,
    prereq: "E2",
    hamniaz: "",
    bgColor: "blue",
  },
  {
    subject: " * پروژه کارشناسی",
    credits: 3,
    prereq: "E6",
    hamniaz: "",
    bgColor: "blue",
  },
  {
    subject: "مبانی ماتریس و جبر خطی",
    credits: 3,
    prereq: "B1",
    hamniaz: "",
    bgColor: "red",
  },
  {
    subject: "مبانی آنالیز ریاضی",
    credits: 3,
    prereq: "B1,A1",
    hamniaz: "",
    bgColor: "blue",
  },
  {
    subject: "نظریه محاسبه",
    credits: 3,
    prereq: "C1",
    hamniaz: "",
    bgColor: "red",
  },
  {
    subject: "مبانی نظریه محاسبه",
    credits: 3,
    prereq: "B1",
    hamniaz: "",
    bgColor: "red",
  },
  {
    subject: "مبانی علوم ریاضی",
    credits: 3,
    prereq: "A1",
    hamniaz: "",
    bgColor: "red",
  },
  {
    subject: "ریاضی عمومی 1",
    credits: 3,
    prereq: "",
    hamniaz: "",
    bgColor: "yellow",
  },
  {
    subject: "نظریه کد گذاری",
    credits: 3,
    prereq: "F1/C2",
    hamniaz: "",
    bgColor: "blue",
  },
  {
    subject: "هوش مصنوعی",
    credits: 4,
    prereq: "C4,B5",
    hamniaz: "",
    bgColor: "red",
  },
  {
    subject: "معادلات دیفرانسیل",
    credits: 3,
    prereq: "A1",
    hamniaz: "",
    bgColor: "yellow",
  },
  {
    subject: "طراحی و تحلیل الگوریتم  ها",
    credits: 3,
    prereq: "C4",
    hamniaz: "",
    bgColor: "red",
  },
  {
    subject: "مبانی آنالیز عددی",
    credits: 3,
    prereq: "B2",
    hamniaz: "",
    bgColor: "red",
  },
  {
    subject: "مبانی جبر",
    credits: 3,
    prereq: "B1",
    hamniaz: "",
    bgColor: "blue",
  },
  {
    subject: "ریاضی عمومی 2",
    credits: 3,
    prereq: "A1",
    hamniaz: "",
    bgColor: "yellow",
  },
  {
    subject: "فیزیک عمومی 1",
    credits: 3,
    prereq: "",
    hamniaz: "",
    bgColor: "yellow",
  },
  {
    subject: "بهینه سازی خطی",
    credits: 3,
    prereq: "F1",
    hamniaz: "",
    bgColor: "red",
  },
  {
    subject: "جبر خطی عددی",
    credits: 3,
    prereq: "F1",
    hamniaz: "",
    bgColor: "red",
  },
  {
    subject: "زبان های برنامه سازی",
    credits: 3,
    prereq: "C4",
    hamniaz: "",
    bgColor: "blue",
  },
  {
    subject: "کامپایلر",
    credits: 3,
    prereq: "C1",
    hamniaz: "",
    bgColor: "blue",
  },
  {
    subject: "اصول سیستم های عامل",
    credits: 4,
    prereq: "C4",
    hamniaz: "",
    bgColor: "red",
  },
  {
    subject: "اصول سیستم های کامپیوتری",
    credits: 4,
    prereq: "B4",
    hamniaz: "",
    bgColor: "red",
  },
  {
    subject: "مبانی ترکیبیات",
    credits: 3,
    prereq: "",
    hamniaz: "",
    bgColor: "red",
  },
  {
    subject: "زبان فارسی",
    credits: 3,
    prereq: "",
    hamniaz: "",
    bgColor: "green",
  },
  {
    subject: "مبانی منطق و نظریه مجموعه ها",
    credits: 3,
    prereq: "B1",
    hamniaz: "",
    bgColor: "red",
  },
  {
    subject: "مقدمه ای بر داده کاوی",
    credits: 3,
    prereq: "",
    hamniaz: "",
    bgColor: "blue",
  },
  {
    subject: " * شبکه های کامپیوتری  ",
    credits: 4,
    prereq: "C3",
    hamniaz: "",
    bgColor: "red",
  },
  {
    subject: "مباحثی در علوم کامپیوتر",
    credits: 3,
    prereq: "",
    hamniaz: "",
    bgColor: "blue",
  },
  {
    subject: "اصول طراحی نرم افزار",
    credits: 4,
    prereq: "C4",
    hamniaz: "",
    bgColor: "red",
  },
  {
    subject: "  ساختمان داده ها  و الگوریتم ها ",
    credits: 4,
    prereq: "B4",
    hamniaz: "",
    bgColor: "red",
  },
  {
    subject: "برنامه سازی پیشرفته",
    credits: 4,
    prereq: "A4",
    hamniaz: "",
    bgColor: "red",
  },
  {
    subject: "مبانی کامپیوتر و برنامه سازی",
    credits: 3,
    prereq: "",
    hamniaz: "",
    bgColor: "yellow",
  },
  {
    subject: "اندیشه اسلامی 2",
    credits: 2,
    prereq: "B6",
    hamniaz: "",
    bgColor: "green",
  },
  {
    subject: "تربیت بدنی 2",
    credits: 1,
    prereq: "F7",
    hamniaz: "",
    bgColor: "green",
  },
  {
    subject: " * اصول مدیریت",
    credits: 3,
    prereq: "",
    hamniaz: "",
    bgColor: "yellow",
  },
  {
    subject: "زبان خارجه",
    credits: 3,
    prereq: "",
    hamniaz: "",
    bgColor: "green",
  },
  {
    subject: "  * پایگاه داده ها ",
    credits: 4,
    prereq: "C4",
    hamniaz: "",
    bgColor: "red",
  },
  {
    subject: "احتمال 1",
    credits: 3,
    prereq: "B5",
    hamniaz: "",
    bgColor: "blue",
  },
  {
    subject: "مبانی احتمال",
    credits: 3,
    prereq: "A1",
    hamniaz: "",
    bgColor: "red",
  },
  {
    subject: " * اصول حساب داری و هزینه یابی",
    credits: 3,
    prereq: "",
    hamniaz: "",
    bgColor: "yellow",
  },
  {
    subject: "دانش خانواده",
    credits: 2,
    prereq: "",
    hamniaz: "",
    bgColor: "green",
  },
  {
    subject: "تاریخ تحلیلی صدر اسلام",
    credits: 2,
    prereq: "",
    hamniaz: "",
    bgColor: "green",
  },
  {
    subject: "تفسیر موضوعی قرآن",
    credits: 2,
    prereq: "",
    hamniaz: "",
    bgColor: "green",
  },
  {
    subject: "روش تحقیق و گزارش نویسی",
    credits: 2,
    prereq: "60 واحد",
    hamniaz: "",
    bgColor: "yellow",
  },
  {
    subject: "انقلاب اسلامی",
    credits: 2,
    prereq: "",
    hamniaz: "",
    bgColor: "green",
  },
  {
    subject: "آیین زندگی",
    credits: 2,
    prereq: "",
    hamniaz: "",
    bgColor: "green",
  },
  {
    subject: "اندیشه اسلامی 1",
    credits: 2,
    prereq: "",
    hamniaz: "",
    bgColor: "green",
  },
  {
    subject: "کارگاه کامپیوتر",
    credits: 1,
    prereq: "",
    hamniaz: "",
    bgColor: "green",
  },
  {
    subject: " ",
    credits: "",
    prereq: "",
    hamniaz: "",
    bgColor: "gray",
  },
  {
    subject: "مهارت های زندگی",
    credits: 2,
    prereq: "",
    hamniaz: "",
    bgColor: "green",
  },
  {
    subject: "",
    credits: "",
    prereq: "",
    hamniaz: "",
    bgColor: "gray",
  },
  {
    subject: "",
    credits: "",
    prereq: "",
    hamniaz: "",
    bgColor: "gray",
  },
  {
    subject: "",
    credits: "",
    prereq: "",
    hamniaz: "",
    bgColor: "gray",
  },
  {
    subject: "",
    credits: "",
    prereq: "",
    hamniaz: "",
    bgColor: "gray",
  },
  {
    subject: "",
    credits: "",
    prereq: "",
    hamniaz: "",
    bgColor: "gray",
  },
  {
    subject: "",
    credits: "",
    prereq: "",
    hamniaz: "",
    bgColor: "gray",
  },
  {
    subject: "",
    credits: "",
    prereq: "",
    hamniaz: "",
    bgColor: "gray",
  },
  {
    subject: "",
    credits: "",
    prereq: "",
    hamniaz: "",
    bgColor: "gray",
  },
  {
    subject: "",
    credits: "",
    prereq: "",
    hamniaz: "",
    bgColor: "gray",
  },
  {
    subject: "",
    credits: "",
    prereq: "",
    hamniaz: "",
    bgColor: "gray",
  },
  {
    subject: "",
    credits: "",
    prereq: "",
    hamniaz: "",
    bgColor: "gray",
  },
  {
    subject: "",
    credits: "",
    prereq: "",
    hamniaz: "",
    bgColor: "gray",
  },
  {
    subject: "",
    credits: "",
    prereq: "",
    hamniaz: "",
    bgColor: "gray",
  },
  {
    subject: "عنوان درس ",
    credits: " واحد ",
    prereq: "پیش نیاز ",
    hamniaz: " هم نیاز ",
    bgColor: "orange",
  },
];
